#frases plantas
frases1 = [
    'pregunta umm...',
    '¿estás preocupado?',
    'porque parece',
    'que todos estamos',
    'a punto de morir?',
    'La gente realmente',
    'trata de evitar la ',
    'consideración de que',
    'van a morir',
    '....',
    'pregunta umm...',
    '¿estás preocupado?',
    'porque parece',
    'que todos estamos',
    'a punto de morir?',
    'La gente realmente',
    'trata de evitar la ',
    'consideración de que',
    'van a morir',
    '....',
    'pregunta umm...',
    '¿estás preocupado?',
    'porque parece',
    'que todos estamos',
    'a punto de morir?',
    'La gente realmente',
    'trata de evitar la ',
    'consideración de que',
    'van a morir',
    '....',
    'pregunta umm...',
    '¿estás preocupado?',
    'porque parece',
    'que todos estamos',
    'a punto de morir?',
    'La gente realmente',
    'trata de evitar la ',
    'consideración de que',
    'van a morir',
    '....',
    'pregunta umm...',
    '¿estás preocupado?',
    'porque parece',
    'que todos estamos',
    'a punto de morir?',
    'La gente realmente',
    'trata de evitar la ',
    'consideración de que',
    'van a morir',
    '....',
    'pregunta umm...',
    '¿estás preocupado?',
    'porque parece',
    'que todos estamos',
    'a punto de morir?',
    'La gente realmente',
    'trata de evitar la ',
    'consideración de que',
    'van a morir',
    '....',
    'pregunta umm...',
    '¿estás preocupado?',
    'porque parece',
    'que todos estamos',
    'a punto de morir?',
    'La gente realmente',
    'trata de evitar la ',
    'consideración de que',
    'van a morir',
    '....',
    'pregunta umm...',
    '¿estás preocupado?',
    'porque parece',
    'que todos estamos',
    'a punto de morir?',
    'La gente realmente',
    'trata de evitar la ',
    'consideración de que',
    'van a morir',
    '....',
    'pregunta umm...',
    '¿estás preocupado?',
    'porque parece',
    'que todos estamos',
    'a punto de morir?',
    'La gente realmente',
    'trata de evitar la ',
    'consideración de que',
    'van a morir',
    '....',
    'pregunta umm...',
    '¿estás preocupado?',
    'porque parece',
    'que todos estamos',
    'a punto de morir?',
    'La gente realmente',
    'trata de evitar la ',
    'consideración de que',
    'van a morir',
    '....',
    'pregunta umm...',
    '¿estás preocupado?',
    'porque parece',
    'que todos estamos',
    'a punto de morir?',
    'La gente realmente',
    'trata de evitar la ',
    'consideración de que',
    'van a morir',
    '....',
    'Sensor a tierra'
]

frases2 = [
    'CAPÍTULO 1',
    'CLANCY GILROY',
    'Si tienen una sobredosis dicen:',
    'Me siento paranoico',
    'pero',
    'lo que quieren decir es:',
    'La marihuana muestra',
    'todas las partes de mi ser',
    'con las que no',
    '....',
    'CAPÍTULO 2',
    'ANNE DEER DOG',
    'Las cosas que nos animan',
    'y nos sanan',
    'no vienen en calcomanías, ',
    '¿sabes?',
    'Se requiere un esfuerzo',
    'Me aterrorizaba que',
    ', si dejaba de beber,',
    'jamás volvería a escribir ',
    'porque necesitaba la miseria.',
    'Pero',
    'esa es una de las mentiras',
    'de la enfermedad…',
    'o',
    'del ego',
    ', que si estás bien',
    'y si eres feliz,',
    'se acabó.',
    '....',
    'CAPÍTULO 3',
    'DARRYL THE FISH',
    'No tienes que mentir',
    'cuando algo está mal.',
    'Si te preguntan:',
    '¿Estás enfermo?',
    'No significa que digas que no',
    ', significa:',
    'Estoy mejorando minuto a minuto',
    '....',
    'CAPÍTULO 4',
    'TRUDDY',
    'Piensa en el perdón',
    'como una liberación',
    'de tu corazón.',
    'De todo estado de rencor',
    ', ira y mala voluntad.',
    'No amaremos',
    'al enemigo',
    'pero no tenemos',
    'que vivir obsesionados',
    'con el daño',
    'que nos hicieron.',
    'Si no tenemos un hogar',
    ', quizá podamos crearlo.',
    'Porque si estás solo',
    ', sabes que hay ',
    'otros',
    'que también lo están.',
    '....',
    'CAPÍTULO 5',
    'BOB',
    'En el momento',
    'en que aceptas',
    'las cosas como son…',
    'ya no tienes que esperar más.',
    'Porque te das cuenta',
    'de que estás bien',
    'donde estás.',
    '....',
    'CAPÍTULO 6',
    'DAVID',
    'Si estás involucrado en tu propia historia',
    ', es como vivir en un pequeño departamento.',
    'Cuando hay poco espacio entre tú',
    'y tus pensamientos',
    'es como si te hubieras mudado a una casa mucho más grande.',
    'Luego hay espacio para invitar a más personas.',
    'Hay espacio para ti y para ellos.',
    '....',
    'CAPÍTULO 7',
    'CLANCY GILROY',
    'Tu mente se va',
    'en un instante.',
    'Despídete de ella',
    ', viejo.',
    'Fluctúas',
    'por el pasado',
    'y el presente.',
    '....',
    'CAPÍTULO 8',
    'MAMÁ DE CLANCY',
    '¿Abrir tu corazón siempre duele?',
    'No, no siempre duele.',
    'Pero cuando se abre',
    ', duele.',
    '¿Qué consejo le darías a la gente que está pasando por esto?',
    'pasamos tanto tiempo',
    'Les diría que',
    'lloren cuando necesiten llorar.'
    'Sensor a tierra'
]
#print (frases[1])
#frases2 [], tomadas por: https://animal.mx/entretenimiento/the-midnight-gospel-frases/
